
obstacle_range: 5.5
raytrace_range: 6.0
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
map_topic: /map
subscribe_to_updates: true

obstacle_layer: 
  origin_z: 0.0
  unknown_threshold: 0
  publish_voxel_map: true
  observation_sources: velodyne_sensor  # from the 3D depth sensor
  velodyne_sensor: {sensor_frame: velodyne,
                    data_type: PointCloud2,
                    topic: /velodyne_points,
                    marking: true,
                    clearing: true,
                    min_obstacle_height: 0.0,
                    max_obstacle_height: 3.00}


global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
cost_scaling_factor: 3.0