trajectory_planner:

# Robot Configuration Parameters
  max_vel_x: 1.0
  min_vel_x: 0.0

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 3.0
  vx_samples: 20
  vtheta_samples: 30
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  heading_lookahead: 0.325
  controller_frequency: 10.0

# Robot Footprint
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    radius: 0.2 # for type "circular"
    vertices: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]] # for type "polygon"
    padding: 0.01

# Cost Weights
  pdist_scale: 1 # higher weight make the stick to global path
  gdist_scale: 1
  occdist_scale: 0.2

  oscillation_reset_dist: 0.25
  escape_reset_dist: 0.10
  escape_reset_theta: 1.57079632679
  escape_vel: -0.1

  dwa: true
  heading_scoring: false
  heading_scoring_timestep: 0.1

  simple_attractor: false

  y_vels: [-0.3, -0.1, 0.1, 0.3]






